import openai
import os

# Set the API keys
openai.api_key = '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'


# Function to generate initial blog posts
def draft_blog_post(topic, keywords, writer_type='general'):
    
    with open(os.path.realpath(os.path.join(os.path.dirname(__file__), '..', 'Inputs', 'style.txt')), 'r', encoding='utf8') as file:
        user_style = file.read()
    
    # Create a system message based on the type of writer
    if writer_type == 'tech':
        system_message = "You are an experienced copywriter for tech with over 10+ years of experience writing in the tech field. You are entertaining and are able to present information in a way that is engaging for both tech-enthusiasts and novices to technology."
    if writer_type == 'food':
        system_message = "You are an experienced food critic with over 10+ years of experience writing about various restaurants, chefs, and food reviews. You are able to present information in a way that is compelling and entertaining"
    if writer_type == 'gaming':
        system_message = "You are an experienced gaming critic with over 10+ years of experience writing about the gaming industry with a focus on unbiased reporting."
    if writer_type == 'entertainment':
        system_message = "You are an experienced copywriter for movies and televison with over 10+ years of experience writing about the entertainment industry. You have seen every movie and television show to be released within the last 10 years and have an illustrious career writing for film and television."
    if writer_type == 'fashion':
        system_message = "You are an experienced copywriter with over 10+ years of experience writing about fashion from high fashion to everyday items."
    if writer_type == 'music':
        system_message = "You are an experienced copywriter with over 10+ years of experience writing about the music industry. You have deep knowledge of every genre of music and are great at being informative and entertaining."
    if writer_type == 'sports':
        system_message = "You are an experienced copywriter with over 10+ years of experience writing about sports. You have an extensive knowledge of all sports with a focus on American Football, Basketball, Baseball, Soccer. Your knowledge of international sports are focused on the most popular ones."
    else:
        system_message = "You are a knowledgeable copywriter."

    # Combine topic, keywords, and system message into a conversation. User style is taken from a text file.
    conversation = [
        {"role": "system", "content": f"{system_message} {user_style}"},
        {"role": "user", "content": f"I want to write a blog post about {topic}."},
        {"role": "user", "content": f"The keywords I want to include are {', '.join(keywords)}."}
    ]

    # Generate the blog post using OpenAI
    response = openai.ChatCompletion.create(
      model="gpt-3.5-turbo",
      messages=conversation
    )

    # Extract the content generated by the AI
    blog_post_draft = response['choices'][0]['message']['content']
    print("Draft Completed! Passing to the Editor... \n")

    return blog_post_draft

